### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by benny-n** [sogrim/technion-sogrim#105]
- [x] ~~Handle 401s after users are idle for a long time - **TEMPORARY SOLUTION** - #103~~ Handled robustly with #168
- [x] Better error handling in server side - #123 
- [x] Error fallback page - #168
