### ISSUE TITLE
Demo & QA fixing Plan for 1.0.0 version

### ISSUE THREAD

**Issue by benny-n** [sogrim/technion-sogrim#21]
Core function side: @liadaram1 
- [x] Add a full flow test for 3 years computer science itinerary.
- [x] Add small tests for each component of the core function independently.
- [x] Add a full flow test for software engineering itinerary.
- [x] messages
- [x] #68 
- [x] adding 2-3 new catalogs (with the BO app)
- [x] מעבר נקודות info icon & change title #85 
- [x] types fe & be #77 
- [x] adding loading state to banner cards when we "סגור את התואר"
- [x] send feedback form (footer) #72 
- [x] אנחנו לא הטכניון disclaimer #86 
- [x] table - min width #94 
- [x] table - grade arrows when editing #94
- [x] #75
- [x] minimal redme.md file
- [x] #84 
- [x] skip import courses step, and manually add all your courses #91 
- [x] inform students about בחירה חופשית for any course that isn't in the DB + FAQ about it #83 
- [x] #78 
- [x] card for null semester 
- [x] BLOCK FOR MOBILE!!!
- [x] bug: can't add new semester to user without semesters #90

**Comment by liadaram1** [comment]
Core function side: @liadaram1 
- [ ] Add a full flow test for 3 years computer science itinerary.
- [ ] Add a full flow test for 3 years computer engineering itinerary.
- [ ] Add small tests for each component of the core function independently.
- [ ] Add a full flow test for 4 years software engineering itinerary.

**Comment by NissanOhana** [comment]
- [ ] messages
- [ ] landing page (check issue) #68 
- [ ] adding 2-3 new catalogs (with the BO app)
- [ ] מעבר נקודות info icon & change title
- [ ] types fe & be
- [ ] adding loading state to banner cards when we "סגור את התואר"
- [ ] send feedback form (footer)
- [ ] אנחנו לא הטכניון disclaimer (footer)
- [ ] table - min width
- [ ] table - grade arrows when editing
- [ ] error falback page
- [ ] domain ?
- [ ] minimal redme.md file
- [ ] add ״בתהליך -  in progress bar + card
